-- Perfect Scan patient portal database
-- Run this whole file once in Supabase Dashboard > SQL Editor.

do $$ begin
  create type public.app_role as enum ('patient', 'admin');
exception
  when duplicate_object then null;
end $$;

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  patient_no bigint generated by default as identity unique,
  role public.app_role not null default 'patient',
  full_name text not null default '',
  email text,
  phone text,
  birth_date date,
  gender text check (gender is null or gender in ('female', 'male')),
  medical_notes text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.appointments (
  id uuid primary key default gen_random_uuid(),
  booking_no bigint generated by default as identity unique,
  patient_id uuid not null references public.profiles(id) on delete cascade,
  service_id text not null check (service_id in ('mri','ct','xray','ultrasound','dexa','pano')),
  branch_id text not null check (branch_id in ('sawalha','orabi')),
  appointment_date date not null,
  appointment_time text not null,
  status text not null default 'confirmed' check (status in ('confirmed','arrived','completed','cancelled')),
  notes text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.reports (
  id uuid primary key default gen_random_uuid(),
  report_code text not null unique,
  patient_id uuid not null references public.profiles(id) on delete cascade,
  service_id text not null check (service_id in ('mri','ct','xray','ultrasound','dexa','pano')),
  branch_id text not null check (branch_id in ('sawalha','orabi')),
  title text not null,
  exam_date date not null default current_date,
  findings text,
  impression text,
  doctor_name text not null default 'د. عيد رمضان البيطار',
  status text not null default 'pending' check (status in ('pending','ready')),
  file_path text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists appointments_patient_date_idx
  on public.appointments(patient_id, appointment_date desc);
create index if not exists reports_patient_date_idx
  on public.reports(patient_id, exam_date desc);

alter table public.profiles add column if not exists email text;

create or replace function public.set_updated_at()
returns trigger
language plpgsql
set search_path = ''
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists profiles_set_updated_at on public.profiles;
create trigger profiles_set_updated_at before update on public.profiles
for each row execute function public.set_updated_at();
drop trigger if exists appointments_set_updated_at on public.appointments;
create trigger appointments_set_updated_at before update on public.appointments
for each row execute function public.set_updated_at();
drop trigger if exists reports_set_updated_at on public.reports;
create trigger reports_set_updated_at before update on public.reports
for each row execute function public.set_updated_at();

create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
begin
  insert into public.profiles (id, full_name, email, phone)
  values (
    new.id,
    coalesce(new.raw_user_meta_data ->> 'full_name', ''),
    new.email,
    nullif(new.raw_user_meta_data ->> 'phone', '')
  )
  on conflict (id) do nothing;
  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
after insert on auth.users
for each row execute function public.handle_new_user();

insert into public.profiles (id, full_name, email, phone)
select
  id,
  coalesce(raw_user_meta_data ->> 'full_name', ''),
  email,
  nullif(raw_user_meta_data ->> 'phone', '')
from auth.users
on conflict (id) do nothing;

create or replace function public.is_admin()
returns boolean
language sql
stable
security definer
set search_path = ''
as $$
  select exists (
    select 1 from public.profiles
    where id = (select auth.uid()) and role = 'admin'
  );
$$;

create or replace function public.cancel_my_appointment(appointment_id uuid)
returns void
language plpgsql
security definer
set search_path = ''
as $$
begin
  update public.appointments
  set status = 'cancelled'
  where id = appointment_id
    and patient_id = (select auth.uid())
    and status = 'confirmed';
end;
$$;

alter table public.profiles enable row level security;
alter table public.appointments enable row level security;
alter table public.reports enable row level security;

drop policy if exists "profiles_select" on public.profiles;
create policy "profiles_select" on public.profiles
for select to authenticated
using (id = (select auth.uid()) or public.is_admin());

drop policy if exists "profiles_update" on public.profiles;
create policy "profiles_update" on public.profiles
for update to authenticated
using (id = (select auth.uid()) or public.is_admin())
with check (id = (select auth.uid()) or public.is_admin());

drop policy if exists "appointments_select" on public.appointments;
create policy "appointments_select" on public.appointments
for select to authenticated
using (patient_id = (select auth.uid()) or public.is_admin());

drop policy if exists "appointments_insert" on public.appointments;
create policy "appointments_insert" on public.appointments
for insert to authenticated
with check (patient_id = (select auth.uid()) or public.is_admin());

drop policy if exists "appointments_admin_update" on public.appointments;
create policy "appointments_admin_update" on public.appointments
for update to authenticated
using (public.is_admin()) with check (public.is_admin());

drop policy if exists "appointments_admin_delete" on public.appointments;
create policy "appointments_admin_delete" on public.appointments
for delete to authenticated using (public.is_admin());

drop policy if exists "reports_select" on public.reports;
create policy "reports_select" on public.reports
for select to authenticated
using (
  public.is_admin()
  or (patient_id = (select auth.uid()) and status = 'ready')
);

drop policy if exists "reports_admin_insert" on public.reports;
create policy "reports_admin_insert" on public.reports
for insert to authenticated with check (public.is_admin());
drop policy if exists "reports_admin_update" on public.reports;
create policy "reports_admin_update" on public.reports
for update to authenticated using (public.is_admin()) with check (public.is_admin());
drop policy if exists "reports_admin_delete" on public.reports;
create policy "reports_admin_delete" on public.reports
for delete to authenticated using (public.is_admin());

revoke all on public.profiles from anon, authenticated;
grant select on public.profiles to authenticated;
grant update (full_name, phone, birth_date, gender, medical_notes) on public.profiles to authenticated;

revoke all on public.appointments from anon, authenticated;
grant select, update, delete on public.appointments to authenticated;
grant insert (patient_id, service_id, branch_id, appointment_date, appointment_time, notes)
  on public.appointments to authenticated;
grant usage, select on sequence public.appointments_booking_no_seq to authenticated;

revoke all on public.reports from anon, authenticated;
grant select, insert, update, delete on public.reports to authenticated;
revoke all on function public.is_admin() from public;
grant execute on function public.is_admin() to authenticated;
revoke all on function public.cancel_my_appointment(uuid) from public;
grant execute on function public.cancel_my_appointment(uuid) to authenticated;
revoke all on function public.handle_new_user() from public;

insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values ('reports', 'reports', false, 52428800, array['application/pdf','image/jpeg','image/png'])
on conflict (id) do update set
  public = false,
  file_size_limit = excluded.file_size_limit,
  allowed_mime_types = excluded.allowed_mime_types;

drop policy if exists "reports_files_select" on storage.objects;
create policy "reports_files_select" on storage.objects
for select to authenticated
using (
  bucket_id = 'reports'
  and (
    public.is_admin()
    or exists (
      select 1 from public.reports r
      where r.file_path = name
        and r.patient_id = (select auth.uid())
        and r.status = 'ready'
    )
  )
);

drop policy if exists "reports_files_admin_insert" on storage.objects;
create policy "reports_files_admin_insert" on storage.objects
for insert to authenticated
with check (bucket_id = 'reports' and public.is_admin());
drop policy if exists "reports_files_admin_update" on storage.objects;
create policy "reports_files_admin_update" on storage.objects
for update to authenticated
using (bucket_id = 'reports' and public.is_admin())
with check (bucket_id = 'reports' and public.is_admin());
drop policy if exists "reports_files_admin_delete" on storage.objects;
create policy "reports_files_admin_delete" on storage.objects
for delete to authenticated
using (bucket_id = 'reports' and public.is_admin());
