const ICONS = {
  scan: '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><circle cx="12" cy="12" r="8"/><circle cx="12" cy="12" r="3"/><path d="M12 2v3M12 19v3M2 12h3M19 12h3"/></svg>',
  home: '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><path d="m3 11 9-8 9 8v9a1 1 0 0 1-1 1h-5v-7H9v7H4a1 1 0 0 1-1-1Z"/></svg>',
  calendar: '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><rect x="3" y="5" width="18" height="16" rx="2"/><path d="M16 3v4M8 3v4M3 10h18"/></svg>',
  file: '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><path d="M14 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V8Z"/><path d="M14 2v6h6M8 13h8M8 17h5"/></svg>',
  user: '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><circle cx="12" cy="8" r="4"/><path d="M4 21a8 8 0 0 1 16 0"/></svg>',
  users: '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><path d="M16 21v-2a4 4 0 0 0-4-4H6a4 4 0 0 0-4 4v2"/><circle cx="9" cy="7" r="4"/><path d="M22 21v-2a4 4 0 0 0-3-3.87M16 3.13a4 4 0 0 1 0 7.75"/></svg>',
  chart: '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><path d="M3 3v18h18M7 16l4-5 4 3 5-7"/></svg>',
  pin: '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><path d="M20 10c0 5-8 12-8 12S4 15 4 10a8 8 0 1 1 16 0Z"/><circle cx="12" cy="10" r="2"/></svg>',
  bell: '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><path d="M18 8a6 6 0 0 0-12 0c0 7-3 7-3 9h18c0-2-3-2-3-9M13.7 21a2 2 0 0 1-3.4 0"/></svg>',
  settings: '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><circle cx="12" cy="12" r="3"/><path d="M19.4 15a1.7 1.7 0 0 0 .34 1.88l.06.06a2 2 0 1 1-2.83 2.83l-.06-.06A1.7 1.7 0 0 0 15 19.4a1.7 1.7 0 0 0-1 .6 1.7 1.7 0 0 0-.4 1.1V21a2 2 0 1 1-4 0v-.09A1.7 1.7 0 0 0 8.6 19.4a1.7 1.7 0 0 0-1.88.34l-.06.06a2 2 0 1 1-2.83-2.83l.06-.06A1.7 1.7 0 0 0 4.6 15a1.7 1.7 0 0 0-.6-1 1.7 1.7 0 0 0-1.1-.4H3a2 2 0 1 1 0-4h.09A1.7 1.7 0 0 0 4.6 8.6a1.7 1.7 0 0 0-.34-1.88l-.06-.06a2 2 0 1 1 2.83-2.83l.06.06A1.7 1.7 0 0 0 9 4.6a1.7 1.7 0 0 0 1-.6 1.7 1.7 0 0 0 .4-1.1V3a2 2 0 1 1 4 0v.09a1.7 1.7 0 0 0 .6 1.51 1.7 1.7 0 0 0 1.88-.34l.06-.06a2 2 0 1 1 2.83 2.83l-.06.06A1.7 1.7 0 0 0 19.4 9c.14.36.35.7.6 1 .3.3.7.4 1.1.4H21a2 2 0 1 1 0 4h-.09A1.7 1.7 0 0 0 19.4 15Z"/></svg>',
  menu: '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><path d="M4 6h16M4 12h16M4 18h16"/></svg>',
  download: '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><path d="M21 15v4a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2v-4M7 10l5 5 5-5M12 15V3"/></svg>',
  image: '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><rect x="3" y="3" width="18" height="18" rx="2"/><circle cx="8.5" cy="8.5" r="1.5"/><path d="m21 15-5-5L5 21"/></svg>',
  logout: '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><path d="M10 17l5-5-5-5M15 12H3M15 3h4a2 2 0 0 1 2 2v14a2 2 0 0 1-2 2h-4"/></svg>'
};

const CENTER = { name: "Perfect Scan", arabicName: "برفكت سكان للأشعة", doctor: "د. عيد رمضان البيطار", whatsapp: "01016391177" };
const BRANCHES = [
  { id: "sawalha", name: "فرع الصوالحة", short: "الصوالحة", address: "شارع 15 مايو، خلف مسجد الصوالحة، أمام قسم ثاني شبرا الخيمة", phone: "01005353962", landline: "44753227", hours: "يوميًا من 2 ظهرًا" },
  { id: "orabi", name: "فرع عرابي", short: "عرابي", address: "برج سيتي مول السلام، أمام كوبري عرابي، الدور الرابع", phone: "01016391177", landline: "42216028", hours: "السبت–الخميس، 11 ص–11 م" }
];
const SERVICES = [
  { id: "mri", code: "MRI", name: "رنين مغناطيسي", desc: "تصوير دقيق للمخ، العمود الفقري والمفاصل", duration: "30–45 دقيقة", prep: "إزالة المعادن وإبلاغ المركز بأي زرعات معدنية", icon: "◉" },
  { id: "ct", code: "CT", name: "أشعة مقطعية", desc: "تصوير مقطعي سريع ودقيق لمناطق الجسم", duration: "10–20 دقيقة", prep: "قد يتطلب صيام 4–6 ساعات حسب نوع الفحص", icon: "◎" },
  { id: "xray", code: "X-RAY", name: "أشعة عادية", desc: "تصوير العظام والصدر ومناطق متعددة", duration: "10 دقائق", prep: "لا تحتاج لتحضير مسبق في أغلب الحالات", icon: "✣" },
  { id: "ultrasound", code: "US", name: "سونار ودوبلر", desc: "فحوصات البطن والحوض والأوعية الدموية", duration: "20–30 دقيقة", prep: "التحضير يختلف حسب منطقة الفحص", icon: "≈" },
  { id: "dexa", code: "DEXA", name: "هشاشة عظام", desc: "قياس كثافة العظام وتقييم خطر الكسور", duration: "15 دقيقة", prep: "تجنب مكملات الكالسيوم يوم الفحص", icon: "⌁" },
  { id: "pano", code: "PANO", name: "بانوراما أسنان", desc: "صورة شاملة للفكين والأسنان", duration: "10 دقائق", prep: "إزالة الحلي والنظارات قبل التصوير", icon: "◌" }
];
const REPORTS = [
  { id: "PS-260825-184", serviceId: "mri", title: "رنين مغناطيسي على الركبة اليمنى", branch: "فرع عرابي", date: "25 أغسطس 2026", status: "جاهز", doctor: "د. عيد رمضان البيطار", finding: "الأربطة الصليبية والغضاريف الهلالية سليمة. يوجد ارتشاح بسيط داخل المفصل دون علامات تمزق حاد.", impression: "ارتشاح بسيط بمفصل الركبة، ولا توجد إصابة رباطية أو غضروفية واضحة." },
  { id: "PS-260812-097", serviceId: "ultrasound", title: "سونار على البطن والحوض", branch: "فرع الصوالحة", date: "12 أغسطس 2026", status: "جاهز", doctor: "د. عيد رمضان البيطار", finding: "الكبد والمرارة والكليتان في الحدود الطبيعية، ولا توجد حصوات أو تجمعات سائلة.", impression: "فحص البطن والحوض بالموجات فوق الصوتية في الحدود الطبيعية." },
  { id: "PS-260830-221", serviceId: "ct", title: "أشعة مقطعية على الجيوب الأنفية", branch: "فرع عرابي", date: "30 أغسطس 2026", status: "قيد المراجعة", doctor: "د. عيد رمضان البيطار" }
];
const initialAppointments = [
  { id: 4108, serviceId: "mri", service: "رنين مغناطيسي", branchId: "orabi", branch: "فرع عرابي", date: "2026-09-02", dateLabel: "الأربعاء، 2 سبتمبر", day: "02", month: "سبتمبر", time: "05:30 م", status: "مؤكد" },
  { id: 3984, serviceId: "ultrasound", service: "سونار ودوبلر", branchId: "sawalha", branch: "فرع الصوالحة", date: "2026-08-12", dateLabel: "الأربعاء، 12 أغسطس", day: "12", month: "أغسطس", time: "03:00 م", status: "مكتمل" }
];

function loadJSON(key, fallback) { try { return JSON.parse(localStorage.getItem(key)) || fallback; } catch { return fallback; } }
const state = { role: localStorage.getItem("perfectscan-role") || null, page: "home", appointments: loadJSON("perfectscan-appointments", initialAppointments), selectedService: null, selectedBranch: null, selectedDate: null, selectedDateLabel: null, selectedSlot: null };
const app = document.getElementById("app");

function brand() { return `<div class="brand-lockup ps-brand"><img class="ps-logo" src="assets/perfect-scan-logo-transparent.png" alt="برفكت سكان - د. عيد رمضان للأشعة"></div>`; }

function roleEntry() {
  return `<main class="entry ps-entry"><section class="entry-brand ps-entry-brand">${brand()}<div class="entry-copy"><span class="eyebrow" style="color:#8ee7d9">بوابة برفكت سكان الرقمية</span><h1>فحصك وتقريرك،<br><em>في رحلة واحدة.</em></h1><p>احجز فحص الأشعة في فرع الصوالحة أو عرابي، تابع موعدك، واستلم التقرير والصور من حسابك بأمان.</p></div><div class="entry-scan-orbit" aria-hidden="true"><span></span><i></i></div><div class="privacy-note">${ICONS.file}<span>نسخة عرض تجريبية — لا تحتوي على بيانات مرضى حقيقية</span></div></section><section class="entry-panel"><div class="login-box"><span class="eyebrow">اختيار بوابة الدخول</span><h2>أهلاً بيك في Perfect Scan</h2><p class="muted">اختار طريقة الدخول لتجربة النظام.</p><div class="role-list"><button class="role-card" data-role="patient"><span class="role-icon">${ICONS.user}</span><span><strong>دخول المريض</strong><span>حجز فحص، متابعة الموعد، وعرض التقارير</span></span><span>‹</span></button><button class="role-card admin" data-role="admin"><span class="role-icon">${ICONS.chart}</span><span><strong>إدارة المركز</strong><span>الحجوزات، الفروع، المرضى، واعتماد التقارير</span></span><span>‹</span></button></div><div class="login-hint">نسخة تجريبية: لا تحتاج إلى بريد إلكتروني أو كلمة مرور.</div></div></section></main>`;
}

const patientNav = [["home","الرئيسية",ICONS.home],["book","احجز فحص",ICONS.scan],["appointments","مواعيدي",ICONS.calendar],["reports","تقاريري وصوري",ICONS.file],["profile","بياناتي",ICONS.user]];
const adminNav = [["dashboard","نظرة عامة",ICONS.chart],["admin-appointments","الحجوزات",ICONS.calendar],["admin-reports","التقارير",ICONS.file],["patients","المرضى",ICONS.users],["branches","الفروع والأجهزة",ICONS.scan],["settings","الإعدادات",ICONS.settings]];

function shell() {
  const isAdmin = state.role === "admin";
  if (isAdmin && ["home","appointments","reports","profile"].includes(state.page)) state.page = "dashboard";
  if (!isAdmin && ["dashboard","admin-appointments","admin-reports","patients","branches","settings"].includes(state.page)) state.page = "home";
  const nav = isAdmin ? adminNav : patientNav;
  const name = isAdmin ? "رنا مصطفى" : "نور أحمد";
  return `<div class="shell"><aside class="sidebar" id="sidebar">${brand()}<nav><ul class="nav-list">${nav.map(([id,label,icon]) => `<li><button class="nav-button ${state.page === id ? "active" : ""}" ${id === "book" ? "data-open-booking" : `data-page="${id}"`}>${icon}<span>${label}</span></button></li>`).join("")}</ul></nav><div class="center-contact"><span>الحجز والاستعلام</span><strong class="num">${CENTER.whatsapp}</strong></div><div class="side-user"><button class="user-chip" id="change-role"><span class="avatar">${name[0]}</span><span><strong>${name}</strong><small>${isAdmin ? "إدارة المركز" : "ملف المريض"}</small></span>${ICONS.logout}</button></div></aside><main class="main"><header class="topbar"><div style="display:flex;align-items:center;gap:12px"><button class="icon-button mobile-menu" id="menu-toggle">${ICONS.menu}</button><h1>${pageTitle()}</h1></div><div class="top-actions"><button class="icon-button" aria-label="الإشعارات">${ICONS.bell}<span class="notif-dot"></span></button></div></header><div class="content">${pageContent()}</div></main></div>`;
}

function pageTitle() { return ({home:"الرئيسية",appointments:"مواعيدي",reports:"تقاريري وصوري",profile:"بياناتي",dashboard:"نظرة عامة","admin-appointments":"إدارة الحجوزات","admin-reports":"إدارة التقارير",patients:"المرضى",branches:"الفروع والأجهزة",settings:"إعدادات المركز"})[state.page] || CENTER.arabicName; }
function pageContent() { const pages={home:patientHome,appointments:appointmentsPage,reports:reportsPage,profile:profilePage,dashboard:adminDashboard,"admin-appointments":adminAppointments,"admin-reports":adminReports,patients:patientsPage,branches:branchesPage,settings:settingsPage}; return `<div class="view">${(pages[state.page] || patientHome)()}</div>`; }

function patientHome() {
  const upcoming = state.appointments.find(item => item.status === "مؤكد");
  return `<section class="scan-hero"><div class="scan-copy"><span class="scan-kicker">Perfect Scan Patient Portal</span><h2>احجز فحصك،<br><em>واستلم نتيجتك هنا.</em></h2><p>اختار نوع الأشعة والفرع والموعد المناسب. بعد الفحص هتلاقي التقرير والصور محفوظين في حسابك.</p><div class="hero-actions"><button class="btn btn-light" data-open-booking>${ICONS.calendar} احجز فحص جديد</button><button class="btn btn-glass" data-page="reports">عرض تقاريري</button></div><div class="hero-trust"><span>✓ تحت إشراف ${CENTER.doctor}</span><span>✓ فرعا الصوالحة وعرابي</span></div></div><div class="scan-visual"><div class="hero-logo-card"><img src="assets/perfect-scan-logo-transparent.png" alt="برفكت سكان - د. عيد رمضان للأشعة"><span>Diagnostic Imaging Center</span></div><div class="scan-status"><i></i><span>خدمات الحجز الإلكتروني متاحة</span><strong>ONLINE</strong></div></div></section>${upcoming ? `<section class="next-scan card"><div class="next-date"><strong>${upcoming.day}</strong><span>${upcoming.month}</span></div><div><span class="eyebrow">موعدك القادم</span><h3>${upcoming.service}</h3><p>${upcoming.branch} · الساعة ${upcoming.time}</p></div><span class="pill success">مؤكد</span><button class="btn btn-secondary" data-page="appointments">تفاصيل الموعد</button></section>` : ""}<section class="section-head"><div><h2>اختار نوع الفحص</h2><p>ابدأ الحجز من الخدمة المطلوبة.</p></div></section><div class="scan-service-grid">${SERVICES.map(serviceCard).join("")}</div><section class="scan-journey"><div class="section-head"><div><h2>رحلة الفحص في 3 خطوات</h2><p>من الحجز لحد استلام النتيجة.</p></div></div><div class="journey-steps"><article><span>01</span><div>${ICONS.calendar}</div><h3>احجز الموعد</h3><p>اختار الفحص والفرع والوقت.</p></article><article><span>02</span><div>${ICONS.scan}</div><h3>اعمل الفحص</h3><p>احضر قبل الموعد بـ15 دقيقة.</p></article><article><span>03</span><div>${ICONS.file}</div><h3>استلم التقرير</h3><p>التقرير والصور يظهروا في حسابك.</p></article></div></section><section class="section-head"><div><h2>فروع Perfect Scan</h2><p>اختار الأقرب ليك أثناء الحجز.</p></div></section><div class="patient-branches">${BRANCHES.map(branchPublicCard).join("")}</div>`;
}

function serviceCard(service) { return `<article class="scan-service card"><div class="service-glyph">${service.icon}</div><div><span class="service-code">${service.code}</span><h3>${service.name}</h3><p>${service.desc}</p></div><div class="service-foot"><span>${service.duration}</span><button class="btn btn-secondary" data-service-book="${service.id}">احجز</button></div></article>`; }
function branchPublicCard(branch) { return `<article class="card ps-branch-card"><div class="branch-pin">${ICONS.pin}</div><div><span class="eyebrow">${branch.name}</span><h3>${branch.address}</h3><p>${branch.hours}</p></div><div class="branch-numbers"><a href="tel:${branch.phone}" class="num">${branch.phone}</a><span class="num">${branch.landline}</span></div></article>`; }

function appointmentsPage() {
  const upcoming=state.appointments.filter(item=>item.status==="مؤكد"), previous=state.appointments.filter(item=>item.status!=="مؤكد");
  const renderList=items=>items.length?`<div class="appointment-list">${items.map(item=>`<article class="card upcoming-card"><div class="appointment-date"><strong>${item.day}</strong><span>${item.month}</span></div><div class="appointment-info"><h3>${item.service}</h3><p>${item.branch} · ${item.dateLabel}</p><p>الساعة ${item.time} · رقم الحجز #${item.id}</p></div><span class="pill ${item.status==="مؤكد"?"success":""}">${item.status}</span>${item.status==="مؤكد"?`<button class="btn btn-danger cancel-booking" data-id="${item.id}">إلغاء الموعد</button>`:`<button class="btn btn-ghost" data-page="reports">عرض التقرير</button>`}</article>`).join("")}</div>`:`<div class="card empty-state"><div class="empty-icon">${ICONS.calendar}</div><h3>مفيش مواعيد هنا</h3><p>ابدأ بحجز فحصك الأول في Perfect Scan.</p><button class="btn btn-primary" data-open-booking>احجز فحص</button></div>`;
  return `<div class="section-head"><div><h2>مواعيدي القادمة</h2><p>كل مواعيد الفحوصات المؤكدة.</p></div><button class="btn btn-primary" data-open-booking>+ حجز فحص</button></div>${renderList(upcoming)}<div class="section-head page-gap"><div><h2>الفحوصات السابقة</h2><p>سجل زياراتك إلى Perfect Scan.</p></div></div>${renderList(previous)}`;
}

function reportsPage() {
  return `<div class="reports-hero"><div><span class="eyebrow">ملف الأشعة الرقمي</span><h2>تقاريرك وصورك محفوظة في مكان واحد</h2><p>كل نتيجة مرتبطة برقم الفحص، الفرع، وتاريخ الزيارة.</p></div><div class="report-count"><strong>${REPORTS.filter(r=>r.status==="جاهز").length}</strong><span>تقارير جاهزة</span></div></div><div class="report-grid">${REPORTS.map(report=>{const service=SERVICES.find(s=>s.id===report.serviceId);return `<article class="card report-card ${report.status!=="جاهز"?"pending":""}"><div class="report-preview"><span>${service.code}</span><div class="image-lines"><i></i><i></i><i></i></div></div><div class="report-body"><div class="report-top"><span class="pill ${report.status==="جاهز"?"success":"warning"}">${report.status}</span><small class="num">${report.id}</small></div><h3>${report.title}</h3><p>${report.branch} · ${report.date}</p><div class="report-actions">${report.status==="جاهز"?`<button class="btn btn-primary view-report" data-report="${report.id}">${ICONS.file} عرض التقرير</button><button class="btn btn-ghost image-viewer">${ICONS.image} الصور</button>`:`<button class="btn btn-ghost" disabled>سيصلك إشعار بعد الاعتماد</button>`}</div></div></article>`}).join("")}</div>`;
}

function profilePage() { return `<div class="section-head"><div><h2>بيانات المريض</h2><p>بياناتك الأساسية المستخدمة في الحجز والتقارير.</p></div></div><div class="profile-grid"><aside class="card profile-summary"><div class="profile-photo">ن أ</div><h3>نور أحمد محمود</h3><p>Patient ID: <span class="num">PS-10284</span></p><div class="summary-box"><div class="summary-row"><span>الفحوصات</span><strong>3</strong></div><div class="summary-row"><span>التقارير الجاهزة</span><strong>2</strong></div></div></aside><form class="card form-card" id="profile-form"><div class="form-grid"><div class="field"><label>الاسم بالكامل</label><input value="نور أحمد محمود"></div><div class="field"><label>رقم الموبايل</label><input value="010 1234 5678"></div><div class="field"><label>الرقم القومي</label><input value="••••••••••1234"></div><div class="field"><label>تاريخ الميلاد</label><input type="date" value="1997-05-18"></div><div class="field"><label>النوع</label><select><option>أنثى</option><option>ذكر</option></select></div><div class="field"><label>البريد الإلكتروني</label><input type="email" value="nour@example.com"></div><div class="field full"><label>ملاحظات مهمة قبل الفحص</label><textarea rows="3" placeholder="حساسية من الصبغة، حمل، منظم ضربات القلب...">لا يوجد</textarea></div></div><div class="form-submit"><button class="btn btn-primary">حفظ البيانات</button></div></form></div>`; }

function adminDashboard() {
  const schedule=[["11:00 ص","سلمى علي","رنين مغناطيسي","الصوالحة","وصل"],["12:30 م","محمد سامي","مقطعية صدر","عرابي","مؤكد"],["02:00 م","هنا أحمد","سونار بطن","الصوالحة","انتظار"],["03:30 م","آدم وليد","بانوراما أسنان","عرابي","مؤكد"]];
  return `<section class="admin-welcome"><div><span class="eyebrow">Perfect Scan Operations</span><h2>صباح الخير يا رنا</h2><p>متابعة الفحوصات والتقارير في الفرعين اليوم.</p></div><button class="btn btn-primary" data-open-booking>+ حجز يدوي</button></section><section class="metric-grid">${[["فحوصات اليوم","36","+8 عن أمس",ICONS.scan],["تقارير جاهزة","24","6 بانتظار الاعتماد",ICONS.file],["مرضى اليوم","31","5 زيارات متابعة",ICONS.users],["الأجهزة المتاحة","7/8","جهاز تحت الصيانة",ICONS.chart]].map(item=>`<article class="card metric-card"><div class="metric-head"><span>${item[0]}</span><span class="metric-icon">${item[3]}</span></div><div class="metric-value num">${item[1]}</div><div class="metric-change">${item[2]}</div></article>`).join("")}</section><section class="dashboard-grid"><div class="card panel"><div class="panel-title"><h3>جدول الفحوصات اليوم</h3><button class="table-action" data-page="admin-appointments">عرض الكل</button></div><div class="schedule-list">${schedule.map((row,index)=>`<div class="schedule-row"><span class="schedule-time">${row[0]}</span><span class="mini-avatar">${row[1][0]}</span><span class="schedule-info"><strong>${row[1]}</strong><span>${row[2]} · فرع ${row[3]}</span></span><span class="pill ${index===0?"success":index===2?"warning":""}">${row[4]}</span></div>`).join("")}</div></div><div class="card panel"><div class="panel-title"><h3>حالة أجهزة التصوير</h3><span class="tiny muted">Live</span></div><div class="device-list">${[["MRI","جاهز",88],["CT","جاهز",72],["X-Ray","جاهز",54],["DEXA","صيانة",0]].map(d=>`<div class="device-row"><span class="device-name">${d[0]}</span><div class="device-bar"><i style="width:${d[2]}%"></i></div><span class="pill ${d[1]==="جاهز"?"success":"warning"}">${d[1]}</span></div>`).join("")}</div></div></section>`;
}

function adminAppointments() { const rows=[["#5128","سلمى علي","رنين مغناطيسي","الصوالحة","11:00 ص","وصل"],["#5129","محمد سامي","مقطعية صدر","عرابي","12:30 م","مؤكد"],["#5130","هنا أحمد","سونار بطن","الصوالحة","02:00 م","انتظار"],["#5131","آدم وليد","بانوراما أسنان","عرابي","03:30 م","مؤكد"]]; return tablePage("حجوزات الفحوصات","تابعي مواعيد الفرعين وحالة وصول المرضى.",["رقم الحجز","المريض","نوع الفحص","الفرع","الموعد","الحالة",""],rows.map(r=>`<tr><td class="num">${r[0]}</td><td><div class="table-person"><span class="mini-avatar">${r[1][0]}</span><strong>${r[1]}</strong></div></td><td>${r[2]}</td><td>فرع ${r[3]}</td><td>${r[4]}</td><td><span class="pill ${r[5]==="وصل"?"success":r[5]==="انتظار"?"warning":""}">${r[5]}</span></td><td><button class="table-action">فتح</button></td></tr>`).join(""),"+ إضافة حجز"); }
function adminReports() { const rows=[["PS-260830-221","نور أحمد","مقطعية جيوب أنفية","د. عيد رمضان","قيد المراجعة"],["PS-260830-220","أحمد طارق","رنين مخ","د. عيد رمضان","جاهز للاعتماد"],["PS-260830-219","ملك أشرف","سونار بطن","د. عيد رمضان","تم الاعتماد"],["PS-260830-218","يوسف عمر","أشعة صدر","د. عيد رمضان","تم الاعتماد"]]; return tablePage("إدارة تقارير الأشعة","راجعي التقارير واعتمديها قبل ظهورها للمريض.",["رقم الفحص","المريض","الفحص","الطبيب","الحالة",""],rows.map((r,i)=>`<tr><td class="num">${r[0]}</td><td><strong>${r[1]}</strong></td><td>${r[2]}</td><td>${r[3]}</td><td><span class="pill ${i>1?"success":"warning"}">${r[4]}</span></td><td><button class="table-action">${i>1?"عرض":"مراجعة"}</button></td></tr>`).join(""),"+ تقرير جديد"); }
function patientsPage() { const rows=[["نور أحمد","PS-10284","010 1234 5678","3 فحوصات","30 أغسطس"],["سلمى علي","PS-10285","011 7832 1098","فحصان","30 أغسطس"],["محمد سامي","PS-10286","012 9921 6380","5 فحوصات","30 أغسطس"],["هنا أحمد","PS-10287","010 6654 2251","فحص واحد","30 أغسطس"]]; return tablePage("ملفات المرضى","بيانات المرضى وسجل الفحوصات والتقارير.",["المريض","Patient ID","الموبايل","الفحوصات","آخر زيارة",""],rows.map(r=>`<tr><td><div class="table-person"><span class="mini-avatar">${r[0][0]}</span><strong>${r[0]}</strong></div></td><td class="num">${r[1]}</td><td class="num">${r[2]}</td><td>${r[3]}</td><td>${r[4]}</td><td><button class="table-action">فتح الملف</button></td></tr>`).join(""),"+ مريض جديد"); }

function branchesPage() { return `<div class="section-head"><div><h2>فروع وأجهزة Perfect Scan</h2><p>بيانات التشغيل والطاقة الاستيعابية لكل فرع.</p></div><button class="btn btn-primary">+ إضافة جهاز</button></div><div class="admin-branch-grid">${BRANCHES.map((branch,index)=>`<article class="card admin-branch"><div class="admin-branch-head"><span class="branch-pin">${ICONS.pin}</span><div><span class="eyebrow">${branch.name}</span><h3>${branch.address}</h3></div><span class="pill success">مفتوح الآن</span></div><div class="branch-stats"><span>مواعيد اليوم<strong>${index===0?19:17}</strong></span><span>الأجهزة المتاحة<strong>${index===0?"4/4":"3/4"}</strong></span><span>نسبة الإشغال<strong>${index===0?"81%":"74%"}</strong></span></div><div class="branch-devices">${(index===0?["MRI","CT","X-Ray","US"]:["MRI","CT","DEXA","PANO"]).map((device,i)=>`<span class="${index===1&&i===2?"maintenance":""}">${device}<small>${index===1&&i===2?"صيانة":"جاهز"}</small></span>`).join("")}</div><div class="admin-branch-foot"><span>${branch.hours}</span><button class="btn btn-ghost">إدارة الفرع</button></div></article>`).join("")}</div>`; }
function settingsPage() { return `<div class="section-head"><div><h2>إعدادات المركز</h2><p>بيانات التواصل والحجز وظهور التقارير.</p></div></div><form class="card form-card" id="settings-form"><div class="form-grid"><div class="field"><label>اسم المركز</label><input value="برفكت سكان للأشعة"></div><div class="field"><label>المدير الطبي</label><input value="د. عيد رمضان البيطار"></div><div class="field"><label>واتساب الحجز</label><input value="01016391177"></div><div class="field"><label>مدة إلغاء الموعد</label><select><option>قبل الموعد بـ 6 ساعات</option></select></div><div class="field"><label>إشعار التقرير</label><select><option>SMS + WhatsApp</option></select></div><div class="field"><label>ظهور التقرير للمريض</label><select><option>بعد اعتماد الطبيب فقط</option></select></div><div class="field full"><label>رسالة تأكيد الحجز</label><textarea rows="3">تم تأكيد موعد فحصك في Perfect Scan. برجاء الحضور قبل الموعد بـ15 دقيقة وإحضار طلب الطبيب.</textarea></div></div><div class="form-submit"><button class="btn btn-primary">حفظ الإعدادات</button></div></form>`; }
function tablePage(title,desc,headers,body,action) { return `<div class="section-head"><div><h2>${title}</h2><p>${desc}</p></div><button class="btn btn-primary">${action}</button></div><div class="card table-card"><div class="table-tools"><input class="mini-search" placeholder="ابحث بالاسم أو الرقم..."><button class="btn btn-ghost">تصفية</button></div><table class="data-table"><thead><tr>${headers.map(h=>`<th>${h}</th>`).join("")}</tr></thead><tbody>${body}</tbody></table></div>`; }

function openBooking(preselectedService=null) {
  state.selectedService=preselectedService; state.selectedBranch=null; state.selectedDate=null; state.selectedDateLabel=null; state.selectedSlot=null;
  const dates=[["2026-08-31","غدًا","31 أغسطس"],["2026-09-01","الثلاثاء","1 سبتمبر"],["2026-09-02","الأربعاء","2 سبتمبر"]], slots=["11:00 ص","12:30 م","02:00 م","03:30 م","05:00 م","06:30 م","08:00 م","09:30 م"];
  document.body.insertAdjacentHTML("beforeend",`<div class="modal-backdrop" id="modal"><div class="modal booking-modal" role="dialog" aria-modal="true"><div class="modal-head"><div><span class="eyebrow">حجز فحص جديد</span><h2>اختار تفاصيل الموعد</h2></div><button class="close-btn close-modal">×</button></div><div class="modal-body"><section class="booking-section"><h3><span>1</span> نوع الفحص</h3><div class="booking-services">${SERVICES.map(s=>`<button class="booking-service ${s.id===state.selectedService?"selected":""}" data-book-service="${s.id}"><b>${s.icon}</b><span><strong>${s.name}</strong><small>${s.code} · ${s.duration}</small></span></button>`).join("")}</div></section><section class="booking-section"><h3><span>2</span> الفرع</h3><div class="booking-branches">${BRANCHES.map(b=>`<button class="branch-option" data-book-branch="${b.id}"><span class="branch-pin">${ICONS.pin}</span><span><strong>${b.name}</strong><small>${b.address}</small></span></button>`).join("")}</div></section><section class="booking-section"><h3><span>3</span> اليوم والوقت</h3><div class="date-options">${dates.map(d=>`<button class="date-option" data-date="${d[0]}" data-date-label="${d[1]}، ${d[2]}"><span>${d[1]}</span><strong>${d[2]}</strong></button>`).join("")}</div><div class="slot-grid">${slots.map(slot=>`<button class="slot" data-book-slot="${slot}">${slot}</button>`).join("")}</div></section><div class="prep-note hidden" id="prep-note"></div><div class="booking-summary"><span>الفحص<strong id="summary-service">—</strong></span><span>الفرع<strong id="summary-branch">—</strong></span><span>الموعد<strong id="summary-date">—</strong></span></div></div><div class="modal-foot"><button class="btn btn-ghost close-modal">إلغاء</button><button class="btn btn-primary" id="confirm-booking" disabled>تأكيد الحجز</button></div></div></div>`);
  bindBookingModal(); updateBookingSummary();
}

function bindBookingModal() {
  document.querySelectorAll(".close-modal").forEach(b=>b.onclick=closeModal); const backdrop=document.getElementById("modal"); backdrop.onclick=e=>{if(e.target===backdrop)closeModal()};
  document.querySelectorAll("[data-book-service]").forEach(b=>b.onclick=()=>{document.querySelectorAll("[data-book-service]").forEach(x=>x.classList.remove("selected"));b.classList.add("selected");state.selectedService=b.dataset.bookService;updateBookingSummary()});
  document.querySelectorAll("[data-book-branch]").forEach(b=>b.onclick=()=>{document.querySelectorAll("[data-book-branch]").forEach(x=>x.classList.remove("selected"));b.classList.add("selected");state.selectedBranch=b.dataset.bookBranch;updateBookingSummary()});
  document.querySelectorAll("[data-date]").forEach(b=>b.onclick=()=>{document.querySelectorAll("[data-date]").forEach(x=>x.classList.remove("selected"));b.classList.add("selected");state.selectedDate=b.dataset.date;state.selectedDateLabel=b.dataset.dateLabel;updateBookingSummary()});
  document.querySelectorAll("[data-book-slot]").forEach(b=>b.onclick=()=>{document.querySelectorAll("[data-book-slot]").forEach(x=>x.classList.remove("selected"));b.classList.add("selected");state.selectedSlot=b.dataset.bookSlot;updateBookingSummary()});
  document.getElementById("confirm-booking").onclick=confirmBooking;
}

function updateBookingSummary() {
  const service=SERVICES.find(s=>s.id===state.selectedService),branch=BRANCHES.find(b=>b.id===state.selectedBranch),serviceEl=document.getElementById("summary-service"); if(!serviceEl)return;
  serviceEl.textContent=service?.name||"—"; document.getElementById("summary-branch").textContent=branch?.name||"—"; document.getElementById("summary-date").textContent=state.selectedDateLabel&&state.selectedSlot?`${state.selectedDateLabel} · ${state.selectedSlot}`:"—";
  const prep=document.getElementById("prep-note"); if(service){prep.classList.remove("hidden");prep.innerHTML=`<strong>التحضير للفحص:</strong> ${service.prep}`}else prep.classList.add("hidden"); document.getElementById("confirm-booking").disabled=!(service&&branch&&state.selectedDate&&state.selectedSlot);
}

function confirmBooking() {
  const service=SERVICES.find(s=>s.id===state.selectedService),branch=BRANCHES.find(b=>b.id===state.selectedBranch),day=state.selectedDate.split("-")[2],month=state.selectedDate.startsWith("2026-08")?"أغسطس":"سبتمبر";
  const booking={id:Math.floor(5000+Math.random()*4000),serviceId:service.id,service:service.name,branchId:branch.id,branch:branch.name,date:state.selectedDate,dateLabel:state.selectedDateLabel,day,month,time:state.selectedSlot,status:"مؤكد"}; state.appointments.unshift(booking); localStorage.setItem("perfectscan-appointments",JSON.stringify(state.appointments));
  document.querySelector(".modal-body").innerHTML=`<div class="success-message"><div class="success-check">✓</div><h3>تم تأكيد موعد الفحص</h3><p class="muted">${service.name} في ${branch.name} — ${state.selectedDateLabel} الساعة ${state.selectedSlot}.</p><div class="summary-box"><div class="summary-row"><span>رقم الحجز</span><strong class="num">#${booking.id}</strong></div><div class="summary-row"><span>العنوان</span><strong>${branch.address}</strong></div><div class="summary-row"><span>التحضير</span><strong>${service.prep}</strong></div></div></div>`; document.querySelector(".modal-foot").innerHTML=`<button class="btn btn-ghost close-modal">العودة للرئيسية</button><button class="btn btn-primary" id="go-appointments">عرض مواعيدي</button>`; document.querySelector(".close-modal").onclick=closeModal; document.getElementById("go-appointments").onclick=()=>{closeModal();state.page="appointments";render()};
}

function openReport(id) {
  const report=REPORTS.find(r=>r.id===id),service=SERVICES.find(s=>s.id===report.serviceId);
  document.body.insertAdjacentHTML("beforeend",`<div class="modal-backdrop" id="modal"><div class="modal report-modal" role="dialog" aria-modal="true"><div class="modal-head"><div><span class="eyebrow">تقرير أشعة معتمد</span><h2>${report.title}</h2></div><button class="close-btn close-modal">×</button></div><div class="modal-body"><div class="report-sheet-head"><div class="report-logo"><img src="assets/perfect-scan-logo-transparent.png" alt="شعار برفكت سكان"></div><div><strong>${CENTER.arabicName}</strong><span>تحت إشراف ${CENTER.doctor}</span></div><span class="pill success">معتمد</span></div><div class="report-meta"><span>رقم الفحص<strong class="num">${report.id}</strong></span><span>المريض<strong>نور أحمد محمود</strong></span><span>نوع الفحص<strong>${service.name}</strong></span><span>التاريخ<strong>${report.date}</strong></span></div><div class="report-section"><h3>وصف الفحص والنتائج</h3><p>${report.finding}</p></div><div class="report-section impression"><h3>الانطباع التشخيصي</h3><p>${report.impression}</p></div><div class="doctor-sign"><span>تمت المراجعة والاعتماد بواسطة</span><strong>${report.doctor}</strong><small>استشاري الأشعة التشخيصية</small></div></div><div class="modal-foot"><button class="btn btn-ghost image-viewer">${ICONS.image} عرض الصور</button><button class="btn btn-primary download-report">${ICONS.download} تحميل PDF</button></div></div></div>`); document.querySelector(".close-modal").onclick=closeModal; document.getElementById("modal").onclick=e=>{if(e.target.id==="modal")closeModal()}; document.querySelector(".image-viewer").onclick=()=>toast("تم فتح عارض صور الأشعة التجريبي"); document.querySelector(".download-report").onclick=()=>toast("بدأ تحميل التقرير التجريبي");
}

function closeModal(){document.getElementById("modal")?.remove()}
function toast(message){const el=document.createElement("div");el.className="toast";el.textContent=message;document.getElementById("toast-region").append(el);setTimeout(()=>el.remove(),2800)}
function bindEvents(){document.querySelectorAll("[data-role]").forEach(b=>b.onclick=()=>{state.role=b.dataset.role;state.page=state.role==="admin"?"dashboard":"home";localStorage.setItem("perfectscan-role",state.role);render();window.scrollTo(0,0)});document.querySelectorAll("[data-page]").forEach(b=>b.onclick=()=>{state.page=b.dataset.page;render();window.scrollTo(0,0)});document.querySelectorAll("[data-open-booking]").forEach(b=>b.onclick=()=>openBooking());document.querySelectorAll("[data-service-book]").forEach(b=>b.onclick=()=>openBooking(b.dataset.serviceBook));document.querySelectorAll(".view-report").forEach(b=>b.onclick=()=>openReport(b.dataset.report));document.querySelectorAll(".image-viewer").forEach(b=>b.onclick=()=>toast("تم فتح عارض صور الأشعة التجريبي"));document.querySelectorAll(".cancel-booking").forEach(b=>b.onclick=()=>{state.appointments=state.appointments.map(i=>i.id===+b.dataset.id?{...i,status:"ملغي"}:i);localStorage.setItem("perfectscan-appointments",JSON.stringify(state.appointments));toast("تم إلغاء الموعد");render()});document.getElementById("change-role")?.addEventListener("click",()=>{localStorage.removeItem("perfectscan-role");state.role=null;state.page="home";render();window.scrollTo(0,0)});document.getElementById("menu-toggle")?.addEventListener("click",()=>document.getElementById("sidebar").classList.toggle("open"));document.getElementById("profile-form")?.addEventListener("submit",e=>{e.preventDefault();toast("تم حفظ بيانات المريض")});document.getElementById("settings-form")?.addEventListener("submit",e=>{e.preventDefault();toast("تم حفظ إعدادات المركز")})}
function render(){app.innerHTML=state.role?shell():roleEntry();bindEvents()}
render();
